# Since this is for University work, all of the code is owned partially by the University
# So it will be a better idea to NEVER EVER ask for money
github:
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
custom:
